import Foundation

/// Claude Code emits its official `Notification` hook when it needs the user.
/// mTerm loads a session-local plugin that turns those events into an allowlisted
/// OSC 777 `terminalSequence`, then maps the sequence back to the pane whose PTY
/// received it. This is deterministic and avoids scraping rendered terminal text.
enum ClaudeIntegration {
    enum AttentionKind: String, CaseIterable, Equatable {
        case permissionPrompt = "permission_prompt"
        case idlePrompt = "idle_prompt"
        case elicitationDialog = "elicitation_dialog"
        case agentNeedsInput = "agent_needs_input"
        case agentCompleted = "agent_completed"

        /// These notifications put Claude in an interaction that can resume
        /// work from a Return without submitting a new top-level prompt.
        var expectsUserResponse: Bool {
            switch self {
            case .permissionPrompt, .elicitationDialog, .agentNeedsInput:
                return true
            case .idlePrompt, .agentCompleted:
                return false
            }
        }

        var notificationTitle: String {
            switch self {
            case .permissionPrompt:
                return "Claude needs permission"
            case .idlePrompt:
                return "Claude is waiting for you"
            case .elicitationDialog, .agentNeedsInput:
                return "Claude needs input"
            case .agentCompleted:
                return "Claude agent finished"
            }
        }

        var notificationBody: String {
            switch self {
            case .permissionPrompt:
                return "Review and approve the pending action."
            case .idlePrompt:
                return "Claude finished responding and is ready for the next prompt."
            case .elicitationDialog:
                return "An MCP server opened a form that needs your response."
            case .agentNeedsInput:
                return "A background agent is waiting for your response."
            case .agentCompleted:
                return "A background agent completed or stopped."
            }
        }
    }

    /// OSC 777 is allowlisted by Claude Code's `terminalSequence` hook output.
    static let oscCode = 777
    static let payloadMarker = "mTerm Claude"
    static let turnStartedPayload = "state;\(payloadMarker);turn_started"
    static let turnCompletedPayload = "state;\(payloadMarker);turn_completed"

    /// Accept only the exact private payload generated by our plugin. Other
    /// programs may legitimately use OSC 777, and must not be able to impersonate
    /// Claude attention events merely by choosing a known notification kind.
    static func parse(_ payload: ArraySlice<UInt8>) -> AttentionKind? {
        guard payload.allSatisfy({ $0 >= 0x20 || $0 == 0x09 }) else { return nil }
        guard let text = String(bytes: payload, encoding: .utf8) else { return nil }
        let fields = text.split(separator: ";", omittingEmptySubsequences: false)
        guard fields.count == 3,
              fields[0] == "notify",
              fields[1] == Substring(payloadMarker) else {
            return nil
        }
        return AttentionKind(rawValue: String(fields[2]))
    }

    /// Lifecycle events are separate from attention notifications. Their
    /// private payloads only drive mTerm's working indicator; they must never be
    /// forwarded to Notification Center.
    static func isTurnCompleted(_ payload: ArraySlice<UInt8>) -> Bool {
        payloadText(payload) == turnCompletedPayload
    }

    static func isTurnStarted(_ payload: ArraySlice<UInt8>) -> Bool {
        payloadText(payload) == turnStartedPayload
    }

    /// SessionStart is the authoritative Claude conversation identity source.
    /// Accept it only from the pane currently owned by Claude so another process
    /// cannot plant a resume locator for the next app launch.
    static func sessionID(
        from payload: ArraySlice<UInt8>,
        foregroundCommand: String?
    ) -> UUID? {
        guard foregroundCommand == "claude",
              let text = payloadText(payload) else { return nil }
        let fields = text.split(separator: ";", omittingEmptySubsequences: false)
        guard fields.count == 3,
              fields[0] == "session",
              fields[1] == Substring(payloadMarker),
              fields[2].count == 36 else { return nil }
        return UUID(uuidString: String(fields[2]))
    }

    private static func payloadText(_ payload: ArraySlice<UInt8>) -> String? {
        guard payload.allSatisfy({ $0 >= 0x20 || $0 == 0x09 }),
              let text = String(bytes: payload, encoding: .utf8) else {
            return nil
        }
        return text
    }

    // MARK: Claude plugin + executable shim

    static var rootDirectory: URL {
        let base = FileManager.default.urls(for: .applicationSupportDirectory,
                                            in: .userDomainMask).first
            ?? URL(fileURLWithPath: NSTemporaryDirectory())
        return base.appendingPathComponent("mTerm/claude-notifications", isDirectory: true)
    }

    static var pluginDirectory: URL {
        rootDirectory.appendingPathComponent("plugin", isDirectory: true)
    }

    static var shimDirectory: URL {
        rootDirectory.appendingPathComponent("shim", isDirectory: true)
    }

    /// Materialize a tiny local Claude plugin and a `claude` PATH shim. The shim
    /// adds `--plugin-dir` only to Claude processes launched inside mTerm, so user
    /// and project settings remain untouched; plugin hooks merge with both.
    @discardableResult
    static func writeFiles() -> Bool {
        let manager = FileManager.default
        let manifestDirectory = pluginDirectory
            .appendingPathComponent(".claude-plugin", isDirectory: true)
        let hooksDirectory = pluginDirectory.appendingPathComponent("hooks", isDirectory: true)
        let scriptsDirectory = pluginDirectory.appendingPathComponent("scripts", isDirectory: true)

        do {
            for directory in [manifestDirectory, hooksDirectory, scriptsDirectory, shimDirectory] {
                try manager.createDirectory(at: directory, withIntermediateDirectories: true)
            }

            try pluginManifest.write(
                to: manifestDirectory.appendingPathComponent("plugin.json"),
                atomically: true,
                encoding: .utf8)
            try hooksConfiguration.write(
                to: hooksDirectory.appendingPathComponent("hooks.json"),
                atomically: true,
                encoding: .utf8)

            let hookURL = scriptsDirectory.appendingPathComponent("notify.sh")
            try hookScript.write(to: hookURL, atomically: true, encoding: .utf8)
            try manager.setAttributes([.posixPermissions: 0o755], ofItemAtPath: hookURL.path)

            let shimURL = shimDirectory.appendingPathComponent("claude")
            try claudeShim.write(to: shimURL, atomically: true, encoding: .utf8)
            try manager.setAttributes([.posixPermissions: 0o755], ofItemAtPath: shimURL.path)
            return true
        } catch {
            return false
        }
    }

    private static let pluginManifest = """
    {
      "name": "mterm-notifications",
      "displayName": "mTerm Notifications",
      "version": "1.0.0",
      "description": "Routes Claude Code attention events to the owning mTerm pane.",
      "author": {
        "name": "mTerm"
      }
    }
    """

    private static let hooksConfiguration: String = {
        let entries = AttentionKind.allCases.map { kind in
            """
                {
                  "matcher": "\(kind.rawValue)",
                  "hooks": [
                    {
                      "type": "command",
                      "command": "${CLAUDE_PLUGIN_ROOT}/scripts/notify.sh",
                      "args": ["\(kind.rawValue)"],
                      "timeout": 5
                    }
                  ]
                }
            """
        }.joined(separator: ",\n")
        return """
        {
          "description": "Tell mTerm when Claude Code needs the user.",
          "hooks": {
            "Notification": [
        \(entries)
            ],
            "SessionStart": [
              {
                "hooks": [
                  {
                    "type": "command",
                    "command": "${CLAUDE_PLUGIN_ROOT}/scripts/notify.sh",
                    "args": ["session_started"],
                    "timeout": 5
                  }
                ]
              }
            ],
            "UserPromptSubmit": [
              {
                "hooks": [
                  {
                    "type": "command",
                    "command": "${CLAUDE_PLUGIN_ROOT}/scripts/notify.sh",
                    "args": ["turn_started"],
                    "timeout": 5
                  }
                ]
              }
            ],
            "Stop": [
              {
                "hooks": [
                  {
                    "type": "command",
                    "command": "${CLAUDE_PLUGIN_ROOT}/scripts/notify.sh",
                    "args": ["turn_completed"],
                    "timeout": 5
                  }
                ]
              }
            ],
            "StopFailure": [
              {
                "hooks": [
                  {
                    "type": "command",
                    "command": "${CLAUDE_PLUGIN_ROOT}/scripts/notify.sh",
                    "args": ["turn_failed"],
                    "timeout": 5
                  }
                ]
              }
            ]
          }
        }
        """
    }()

    /// Read stdin before exiting so Claude never races a closed hook input pipe.
    /// Only SessionStart extracts its official session_id; no branch reads prompt,
    /// transcript, tool, or assistant content.
    private static let hookScript = """
    #!/bin/sh
    input="$(cat)"
    case "$1" in
      session_started)
        session_id="$(printf '%s' "$input" | /usr/bin/plutil -extract session_id raw -o - - 2>/dev/null || true)"
        case "$session_id" in
          ????????-????-????-????-????????????)
            case "$session_id" in
              *[!0123456789abcdefABCDEF-]*) ;;
              *)
                printf '{"terminalSequence":"\\\\u001b]777;session;mTerm Claude;%s\\\\u0007"}\\n' "$session_id"
                ;;
            esac
            ;;
        esac
        ;;
      permission_prompt|idle_prompt|elicitation_dialog|agent_needs_input|agent_completed)
        printf '{"terminalSequence":"\\\\u001b]777;notify;mTerm Claude;%s\\\\u0007"}\\n' "$1"
        ;;
      turn_started)
        printf '{"terminalSequence":"\\\\u001b]777;state;mTerm Claude;turn_started\\\\u0007"}\\n'
        ;;
      turn_completed)
        printf '{"terminalSequence":"\\\\u001b]777;state;mTerm Claude;turn_completed\\\\u0007"}\\n'
        ;;
      turn_failed)
        # StopFailure ignores hook output, so write the non-notifying state
        # sequence to the pane PTY captured by the executable shim.
        case "${MTERM_CLAUDE_TTY:-}" in
          /dev/tty*)
            printf '\\033]777;state;mTerm Claude;turn_completed\\007' >"$MTERM_CLAUDE_TTY" 2>/dev/null || true
            ;;
        esac
        ;;
    esac
    """

    /// Remove this shim's directory from zsh's path array before resolving the
    /// real Claude executable, preventing recursion while preserving every
    /// argument supplied by the user.
    private static let claudeShim = """
    #!/bin/zsh
    shim_dir="${0:A:h}"
    plugin_dir="${shim_dir:h}/plugin"
    path=(${path:#${shim_dir}})
    real_claude="$(command -v claude)"
    if [[ -z "$real_claude" || "$real_claude" == "$0" ]]; then
      print -u2 "mTerm: could not find the Claude Code executable"
      exit 127
    fi
    unset MTERM_CLAUDE_TTY
    mterm_claude_tty="$(tty 2>/dev/null)"
    if [[ "$mterm_claude_tty" == /dev/tty* ]]; then
      export MTERM_CLAUDE_TTY="$mterm_claude_tty"
    fi
    exec "$real_claude" --plugin-dir "$plugin_dir" "$@"
    """ + "\n"
}
